from .Noun import Noun
from .Verb import Verb
from .Adjective import Adjective
from .WordSet import WordSet
from .TemplateFactory import TemplateFactory
from .Template import Template
from .RomanticTemplateFactory import PhilosophicalTemplateFactory
from .PhilosophicalTemplateFactory import RomanticTemplateFactory
from .GangstaTemplateFactory import GangstaTemplateFactory