from .Adjective import Adjective
from .GangstaTemplateFactory import GangstaTemplateFactory
from .Noun import Noun
from .PhilosophicalTemplateFactory import RomanticTemplateFactory
from .RomanticTemplateFactory import PhilosophicalTemplateFactory
from .Template import Template
from .TemplateFactory import TemplateFactory
from .Verb import Verb
from .WordSet import WordSet