services:
  server:
    build:
      context: .
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lab3
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: ./migration
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"



volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
