services:
  db:
    image: postgres:latest
    container_name: lab3_db
    environment:
      POSTGRES_DB: lab3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
